<?php

namespace ContainerC2KUeIF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Mwnl61dService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mwnl61d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mwnl61d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\TaskController::getTasks' => ['privates', '.service_locator.H5Unf_H.App\\Controller\\TaskController::getTasks()', 'getTaskControllergetTasksService', true],
            'App\\Controller\\TaskController::getTask' => ['privates', '.service_locator.YeIKSPi.App\\Controller\\TaskController::getTask()', 'getTaskControllergetTaskService', true],
            'App\\Controller\\TaskController::createTask' => ['privates', '.service_locator.YXjt9NY.App\\Controller\\TaskController::createTask()', 'getTaskControllercreateTaskService', true],
            'App\\Controller\\TaskController::updateTask' => ['privates', '.service_locator.r51IfGL.App\\Controller\\TaskController::updateTask()', 'getTaskControllerupdateTaskService', true],
            'App\\Controller\\TaskController::deleteTask' => ['privates', '.service_locator.b3zDahO.App\\Controller\\TaskController::deleteTask()', 'getTaskControllerdeleteTaskService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\TaskController:getTasks' => ['privates', '.service_locator.H5Unf_H.App\\Controller\\TaskController::getTasks()', 'getTaskControllergetTasksService', true],
            'App\\Controller\\TaskController:getTask' => ['privates', '.service_locator.YeIKSPi.App\\Controller\\TaskController::getTask()', 'getTaskControllergetTaskService', true],
            'App\\Controller\\TaskController:createTask' => ['privates', '.service_locator.YXjt9NY.App\\Controller\\TaskController::createTask()', 'getTaskControllercreateTaskService', true],
            'App\\Controller\\TaskController:updateTask' => ['privates', '.service_locator.r51IfGL.App\\Controller\\TaskController::updateTask()', 'getTaskControllerupdateTaskService', true],
            'App\\Controller\\TaskController:deleteTask' => ['privates', '.service_locator.b3zDahO.App\\Controller\\TaskController::deleteTask()', 'getTaskControllerdeleteTaskService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\TaskController::getTasks' => '?',
            'App\\Controller\\TaskController::getTask' => '?',
            'App\\Controller\\TaskController::createTask' => '?',
            'App\\Controller\\TaskController::updateTask' => '?',
            'App\\Controller\\TaskController::deleteTask' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\TaskController:getTasks' => '?',
            'App\\Controller\\TaskController:getTask' => '?',
            'App\\Controller\\TaskController:createTask' => '?',
            'App\\Controller\\TaskController:updateTask' => '?',
            'App\\Controller\\TaskController:deleteTask' => '?',
        ]);
    }
}
