<?php

namespace ContainerC2KUeIF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskControllerupdateTaskService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.r51IfGL.App\Controller\TaskController::updateTask()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.r51IfGL.App\\Controller\\TaskController::updateTask()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'taskRepository' => ['privates', 'App\\Repository\\TaskRepository', 'getTaskRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'serializer' => ['privates', '.errored.hd0ISEa', NULL, 'Cannot determine controller argument for "App\\Controller\\TaskController::updateTask()": the $serializer argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Serializer\\SerializerInterface".'],
        ], [
            'taskRepository' => 'App\\Repository\\TaskRepository',
            'entityManager' => '?',
            'serializer' => '?',
        ]))->withContext('App\\Controller\\TaskController::updateTask()', $container);
    }
}
