<?php

namespace ContainerC2KUeIF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskControllercreateTaskService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YXjt9NY.App\Controller\TaskController::createTask()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YXjt9NY.App\\Controller\\TaskController::createTask()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'serializer' => ['privates', '.errored.1qo4oif', NULL, 'Cannot determine controller argument for "App\\Controller\\TaskController::createTask()": the $serializer argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Serializer\\SerializerInterface".'],
        ], [
            'entityManager' => '?',
            'serializer' => '?',
        ]))->withContext('App\\Controller\\TaskController::createTask()', $container);
    }
}
