<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTfUybcK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTfUybcK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTfUybcK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTfUybcK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTfUybcK\App_KernelDevDebugContainer([
    'container.build_hash' => 'TfUybcK',
    'container.build_id' => '814eff48',
    'container.build_time' => 1740048953,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTfUybcK');
